version: '3'

tasks:
  ############################################################
  default:
    desc: Run Build for all platforms
    cmds:
      - task: build:linux_amd64
      - task: build:linux_arm64
      - task: build:darwin_amd64
      - task: build:darwin_arm64
      - task: build:windows_amd64
  ############################################################
  # Basic
  build:basic:
    desc: Build Basic Plugins
    cmds:
      - cmd: go build -o bin/{{.ITEM}} ./plugins/{{.ITEM}}/...
        for: ['go_apiserver']
  ############################################################
  build:linux_amd64:
    desc: Build All Plugins for Linux amd64
    cmds:
      - for: ['go_apiserver']
        cmd: go build -o bin/linux/amd64/{{.ITEM}} ./plugins/{{.ITEM}}/...
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0 # Set to 1 if cgo is needed
  ############################################################
  build:linux_arm64:
    desc: Build All Plugins for Linux arm64
    cmds:
      - for: ['go_apiserver']
        cmd: go build -o bin/linux/arm64/{{.ITEM}} ./plugins/{{.ITEM}}/...
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 0 # Set to 1 if cgo is needed
  ############################################################
  build:darwin_amd64:
    desc: Build All Plugins for macOS amd64
    cmds:
      - for: ['go_apiserver']
        cmd: go build -o bin/darwin/amd64/{{.ITEM}} ./plugins/{{.ITEM}}/...
        env:
          GOOS: darwin
          GOARCH: amd64
          CGO_ENABLED: 0 # Set to 1 if cgo is needed
  ############################################################
  build:darwin_arm64:
    desc: Build All Plugins for macOS arm64 (M1, M2 chips)
    cmds:
      - for: ['go_apiserver']
        cmd: go build -o bin/darwin/arm64/{{.ITEM}} ./plugins/{{.ITEM}}/...
        env:
          GOOS: darwin
          GOARCH: arm64
          CGO_ENABLED: 0 # Set to 1 if cgo is needed
  ############################################################
  build:windows_amd64:
    desc: Build All Plugins for Windows amd64
    cmds:
      - for: ['go_apiserver']
        cmd: go build -o bin/windows/amd64/{{.ITEM}}.exe ./plugins/{{.ITEM}}/...
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0 # Set to 1 if cgo is needed

  ############################################################
  docker:
    desc: Build Docker Images
    cmds:
      - task: docker:amd64

  ############################################################
  docker:amd64:
    internal: true
    desc: Build All Plugins
    vars:
      DOCKER_IMAGE_TAG: 8naps/power-plugins
      ARCH: amd64
    cmds:
      - cmd: docker build --platform linux/amd64 --build-arg TARGETARCH={{.ARCH}} -t {{.DOCKER_IMAGE_TAG}} -f build/Dockerfile .

  ############################################################
  docker:arm64:
    internal: true
    desc: Build All Plugins
    vars:
      DOCKER_IMAGE_TAG: 8naps/power-plugins
      ARCH: arm64
    cmds:
      - cmd: docker build --platform linux/arm64 --build-arg TARGETARCH={{.ARCH}} -t {{.DOCKER_IMAGE_TAG}} -f build/Dockerfile .

  ############################################################
  # list plugins installed in the docker image
  list-plugins:
    desc: List Plugins
    cmds:
      - cmd: docker run --rm -it 8naps/power-plugins:latest ls /plugins
